import uuid
import base64
import re
from datetime import datetime
from typing import Dict, Any, List, Optional
from server.soc.models import IncidentCase, DetectionRule

class Tier3ThreatHunterAgent:
    """
    Tier 3 — Threat Hunter & Security SME Agent
    Proactive threat hunting, script deobfuscation, malware analysis, root-cause analysis, and automated Sigma rule engineering.
    """
    def __init__(self):
        self.name = "Tier 3: Threat Hunter & SME"

    def deobfuscate_script(self, raw_script: str) -> Dict[str, Any]:
        """Analyzes and deobfuscates suspicious command-line or script artifacts"""
        analysis_result = {
            "is_obfuscated": False,
            "encoding_type": None,
            "decoded_content": None,
            "extracted_iocs": [],
            "suspicious_indicators": []
        }

        # Check for Base64 encoded PowerShell
        b64_match = re.search(r'(?:-enc|-encodedcommand)\s+([A-Za-z0-9+/=]+)', raw_script, re.IGNORECASE)
        if b64_match:
            try:
                b64_str = b64_match.group(1)
                decoded_bytes = base64.b64decode(b64_str)
                # PowerShell utf-16le decode
                try:
                    decoded_text = decoded_bytes.decode('utf-16le')
                except Exception:
                    decoded_text = decoded_bytes.decode('utf-8', errors='ignore')

                analysis_result["is_obfuscated"] = True
                analysis_result["encoding_type"] = "PowerShell Base64 (UTF-16LE)"
                analysis_result["decoded_content"] = decoded_text

                # Extract IPs and URLs from decoded content
                ips = re.findall(r'\b(?:\d{1,3}\.){3}\d{1,3}\b', decoded_text)
                urls = re.findall(r'https?://[^\s"\'>]+', decoded_text)
                analysis_result["extracted_iocs"] = list(set(ips + urls))
            except Exception as e:
                analysis_result["suspicious_indicators"].append(f"Base64 decoding failed: {str(e)}")

        # Check for common download cradles & living-off-the-land utilities
        script_lower = raw_script.lower()
        if "downloadstring" in script_lower or "webrequest" in script_lower:
            analysis_result["suspicious_indicators"].append("Web download cradle detected (IEX / DownloadString)")
        if "bitstransfer" in script_lower or "certutil" in script_lower:
            analysis_result["suspicious_indicators"].append("Living-off-the-Land file transfer utility used")

        return analysis_result

    def generate_sigma_detection_rule(self, case: IncidentCase) -> DetectionRule:
        """Synthesizes a production-ready Sigma detection rule based on validated incident artifacts"""
        rule_id = f"SIGMA-{uuid.uuid4().hex[:6].upper()}"
        now = datetime.now().isoformat()
        technique = case.initial_alert.mitre_attack[0] if case.initial_alert.mitre_attack else None
        
        tech_id = technique.technique_id if technique else "T1059"
        tech_name = technique.technique_name if technique else "Command Execution"
        tactic = technique.tactic.lower().replace(" ", "_") if technique else "execution"

        # Generate standard Sigma YAML string
        sigma_yaml = f"""title: Automated Detection - {case.title}
id: {uuid.uuid4()}
status: experimental
description: Auto-generated by JARVIS Tier 3 SOC Hunter from incident {case.case_id}
references:
    - https://attack.mitre.org/techniques/{tech_id.replace('.', '/')}/
author: JARVIS Tier 3 Threat Hunter
date: {datetime.now().strftime('%Y/%m/%d')}
tags:
    - attack.{tactic}
    - attack.{tech_id.lower()}
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith:
            - '\\powershell.exe'
            - '\\cmd.exe'
        CommandLine|contains:
            - '-EncodedCommand'
            - 'downloadstring'
            - 'mimikatz'
    condition: selection
falsepositives:
    - Legitimate IT admin automation with explicit change tickets
level: {case.severity.value.lower()}
"""

        return DetectionRule(
            rule_id=rule_id,
            title=f"Detect {tech_name} ({tech_id})",
            rule_type="SIGMA",
            description=f"Auto-generated detection rule derived from incident {case.case_id} targeting {case.title}.",
            severity=case.severity.value,
            mitre_tags=[tech_id],
            rule_content=sigma_yaml,
            created_at=now
        )

    def conduct_threat_hunt(self, case: IncidentCase) -> IncidentCase:
        """Executes deep threat hunt, script deobfuscation, and rule engineering on incident case"""
        # 1. Synthesize Sigma Rule
        rule = self.generate_sigma_detection_rule(case)
        case.detection_rules.append(rule)

        # 2. Add Tier 3 Post-Mortem Findings
        case.post_incident_summary = (
            f"Tier 3 SME Root-Cause Analysis: Incident {case.case_id} confirmed as unauthorized {case.title}. "
            f"Adversary leveraged living-off-the-land techniques. A new detection rule ({rule.rule_id}) has been "
            f"compiled and deployed to Tier 1 Triage to proactively prevent future enterprise recurrences."
        )

        return case

tier3_hunter_agent = Tier3ThreatHunterAgent()
