import uuid
import base64
import re
from datetime import datetime
from typing import Dict, Any, List, Optional
from server.soc.base_soc_agent import BaseSocAgent
from server.soc.models import (
    IncidentContext,
    IncidentCase,
    DetectionRule,
    AgentFinding,
    AgentExecutionPhase
)

class Tier3ThreatHunterAgent(BaseSocAgent):
    """
    Tier 3 — Threat Hunter & Security SME Agent
    Proactive threat hunting, script deobfuscation, malware analysis, root-cause analysis, and automated Sigma rule engineering.
    """
    def __init__(self):
        super().__init__(
            name="tier3_hunter_agent",
            role_title="Tier 3 Threat Hunter & SME",
            description="Executes proactive hypothesis hunting, script deobfuscation, root-cause analysis, and automated Sigma detection engineering."
        )

    def deobfuscate_script(self, raw_script: str) -> Dict[str, Any]:
        """Analyzes and deobfuscates suspicious command-line or script artifacts"""
        analysis_result = {
            "is_obfuscated": False,
            "encoding_type": None,
            "decoded_content": None,
            "extracted_iocs": [],
            "suspicious_indicators": []
        }

        # Check for Base64 encoded PowerShell
        b64_match = re.search(r'(?:-enc|-encodedcommand)\s+([A-Za-z0-9+/=]+)', raw_script, re.IGNORECASE)
        if b64_match:
            try:
                b64_str = b64_match.group(1)
                decoded_bytes = base64.b64decode(b64_str)
                try:
                    decoded_text = decoded_bytes.decode('utf-16le')
                except Exception:
                    decoded_text = decoded_bytes.decode('utf-8', errors='ignore')

                analysis_result["is_obfuscated"] = True
                analysis_result["encoding_type"] = "PowerShell Base64 (UTF-16LE)"
                analysis_result["decoded_content"] = decoded_text

                ips = re.findall(r'\b(?:\d{1,3}\.){3}\d{1,3}\b', decoded_text)
                urls = re.findall(r'https?://[^\s"\'>]+', decoded_text)
                analysis_result["extracted_iocs"] = list(set(ips + urls))
            except Exception as e:
                analysis_result["suspicious_indicators"].append(f"Base64 decoding failed: {str(e)}")

        script_lower = raw_script.lower()
        if "downloadstring" in script_lower or "webrequest" in script_lower:
            analysis_result["suspicious_indicators"].append("Web download cradle detected (IEX / DownloadString)")
        if "bitstransfer" in script_lower or "certutil" in script_lower:
            analysis_result["suspicious_indicators"].append("Living-off-the-Land file transfer utility used")

        return analysis_result

    def generate_sigma_detection_rule(self, case: IncidentContext) -> DetectionRule:
        """Synthesizes a production-ready Sigma detection rule based on validated incident artifacts"""
        rule_id = f"SIGMA-{uuid.uuid4().hex[:6].upper()}"
        now = datetime.now().isoformat()
        tech = case.mitre_attack[0] if case.mitre_attack else None
        if not tech and case.initial_alert and case.initial_alert.mitre_attack:
            tech = case.initial_alert.mitre_attack[0]
            
        tech_id = tech.technique_id if tech else "T1059"
        tech_name = tech.technique_name if tech else "Command Execution"
        tactic = tech.tactic.lower().replace(" ", "_") if tech else "execution"

        sigma_yaml = f"""title: Automated Detection - {case.title}
id: {uuid.uuid4()}
status: experimental
description: Auto-generated by JARVIS Tier 3 SOC Hunter from incident {case.case_id}
references:
    - https://attack.mitre.org/techniques/{tech_id.replace('.', '/')}/
author: JARVIS Tier 3 Threat Hunter
date: {datetime.now().strftime('%Y/%m/%d')}
tags:
    - attack.{tactic}
    - attack.{tech_id.lower()}
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith:
            - '\\powershell.exe'
            - '\\cmd.exe'
        CommandLine|contains:
            - '-EncodedCommand'
            - 'downloadstring'
            - 'mimikatz'
    condition: selection
falsepositives:
    - Legitimate IT admin automation with explicit change tickets
level: {case.severity.value.lower()}
"""
        return DetectionRule(
            rule_id=rule_id,
            title=f"Detect {tech_name} ({tech_id})",
            rule_type="SIGMA",
            description=f"Auto-generated detection rule derived from incident {case.case_id} targeting {case.title}.",
            severity=case.severity.value,
            mitre_tags=[tech_id],
            rule_content=sigma_yaml,
            created_at=now
        )

    def conduct_threat_hunt(self, case: IncidentContext) -> IncidentContext:
        """Executes deep threat hunt, script deobfuscation, and rule engineering on incident case"""
        rule = self.generate_sigma_detection_rule(case)
        case.detection_rules.append(rule)

        case.post_incident_summary = (
            f"Tier 3 SME Root-Cause Analysis: Incident {case.case_id} confirmed as unauthorized {case.title}. "
            f"Adversary leveraged living-off-the-land techniques. A new detection rule ({rule.rule_id}) has been "
            f"compiled and deployed to Tier 1 Triage to proactively prevent future enterprise recurrences."
        )

        case.agent_findings[self.name] = AgentFinding(
            agent_name=self.name,
            role_title=self.role_title,
            phase=AgentExecutionPhase.REPORT,
            confidence=0.98,
            summary=f"Tier 3 Threat Hunt concluded. Synthesized detection rule {rule.rule_id}.",
            structured_data={"rule_id": rule.rule_id, "mitre": [t.technique_id for t in case.mitre_attack]},
            recommendations=["Deploy detection rule to production SIEM", "Execute retrospective IOC hunt across historical 90-day logs"]
        )

        return case

tier3_hunter_agent = Tier3ThreatHunterAgent()
